### ISSUE TITLE
Closing the client after selecting a character then restarting the client prevents you from selecting that character

### ISSUE THREAD

**Issue by bradleywolinski** [procro04/clue-less#20] opened 2024-04-12 00:41 UTC
1. Start game as you normally would, enter user name
2. Select character.
3. Close GUI (just the monogame, not the server)
4. Reopen GUI
5. Enter user name and select same character
6. error popup
![image](https://github.com/procro04/clue-less/assets/83616477/9235cf4d-7beb-4403-add6-20b069cc190a)

**Comment by icanhearyousmile** [comment] 2024-04-13 00:58
So, when you are running the game locally, having the Server project running in Debug mode IS acting like the server - in this case, you have to stop the server/stop debugging to get a reset after the game has begun. 

On the hosted server, there is a button I added (as demonstrated in the instructions) that says "Restart server" and that will automatically kill and restart the server, which will allow you to go ahead and start the game again after exiting. You can shortcut to the kill switch by just doing the accusation of the solution as is printed out in the console on the hosted server. 

Because we're not developing a "real" production-ready game, I didn't put in the work (and it would be _a lot of work_) to do like session tracking and all of that for you to be able to leave and rejoin an active session and all of that. 

The only way, therefore, is a total reset of the server. For these reasons, I am going to close this as expected behavior given the constraints and the way the game server is set up locally.

**Closed as completed by icanhearyousmile** 2024-04-13 00:58 UTC
Labels: bug
